import type { Metadata } from "next";
import { Suspense } from "react";
import { Poppins } from "next/font/google";
import "./globals.css";
import Cursor from "../components/Cursor";
import Navbar from "../components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Venture Craft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-poppins antialiased`}
      >
        <Suspense fallback={null}>
          <Navbar />
        </Suspense>
        <div style={{ position: 'fixed', top: '100px', left: 0, width: '100%', height: '50px', backgroundColor: 'red', color: 'white', zIndex: 9999, textAlign: 'center', fontWeight: 'bold', fontSize: '24px', lineHeight: '50px' }}>
          PROJECT UPDATED - VERIFICATION BANNER
        </div>
        <Cursor />
        {children}
      </body>
    </html>
  );
}
